name: YetiSquat
main: net.yeticraft.squatingyeti.yetisquat.YetiSquat
version: 1.0
description: >
             YetiSquat
commands:
  squat: 
    description: hides a yeti from other players
    usage: /squat
  stand:
    description: reveal your true yeti to other players
    usage: /stand
    
permissions:
  yetisquat.squat:
    description: Allows a player to squat
    default: op
  yetisquat.see:
    description: Allows a player to see anyone that is squatting
    default: op